QUESTIONNAIRE = {
    "sections": [
        {
            "id": "basics",
            "title": "Let's get to know you",
            "subtitle": "The basics — so JAY can stop calling you 'hey you'",
            "icon": "user",
            "questions": [
                {
                    "id": "username",
                    "type": "text_input",
                    "question": "Pick a username",
                    "subtitle": "This is your identity in the JAY community. Make it iconic.",
                    "placeholder": "e.g. glow_goddess, skincare_priya",
                    "validation": {
                        "min_length": 3,
                        "max_length": 30,
                        "pattern": "^[a-zA-Z0-9_]+$",
                    },
                    "required": True,
                },
                {
                    "id": "date_of_birth",
                    "type": "date_picker",
                    "question": "When's your birthday?",
                    "subtitle": "Your age changes everything — a 20-year-old's skin and a 35-year-old's skin live on different planets",
                    "validation": {"min_age": 13, "max_age": 100},
                    "required": False,
                },
                {
                    "id": "gender",
                    "type": "single_select",
                    "question": "How do you identify?",
                    "subtitle": "Hormones play a big role in skin behavior",
                    "options": [
                        {"value": "male", "label": "Male"},
                        {"value": "female", "label": "Female"},
                        {"value": "non_binary", "label": "Non-binary"},
                        {"value": "prefer_not_to_say", "label": "Prefer not to say"},
                    ],
                    "required": False,
                },
                {
                    "id": "location",
                    "type": "location_picker",
                    "question": "Where are you based?",
                    "subtitle": "Climate, humidity, and pollution levels affect your skin more than you think",
                    "fields": [
                        {"id": "location_city", "placeholder": "City", "required": False},
                        {"id": "location_state", "placeholder": "State", "required": False},
                        {
                            "id": "location_country",
                            "placeholder": "Country",
                            "default": "India",
                            "required": False,
                        },
                    ],
                },
            ],
        },
        {
            "id": "skin",
            "title": "Your skin, decoded",
            "subtitle": "No judgment zone — just honest skin talk",
            "icon": "sparkles",
            "questions": [
                {
                    "id": "skin_type",
                    "type": "single_select_card",
                    "question": "What's your skin type?",
                    "subtitle": "If you're not sure, pick the one that sounds most like you",
                    "options": [
                        {
                            "value": "oily",
                            "label": "Oily",
                            "description": "Shiny by noon, blotting papers are your best friend",
                            "emoji": "💧",
                        },
                        {
                            "value": "dry",
                            "label": "Dry",
                            "description": "Tight, flaky, always thirsty for moisture",
                            "emoji": "🏜️",
                        },
                        {
                            "value": "combination",
                            "label": "Combination",
                            "description": "Oily T-zone but dry cheeks — your skin can't decide",
                            "emoji": "🎭",
                        },
                        {
                            "value": "normal",
                            "label": "Normal",
                            "description": "Balanced, rarely breaks out — you hit the genetic lottery",
                            "emoji": "✨",
                        },
                    ],
                    "required": True,
                },
                {
                    "id": "fitzpatrick_type",
                    "type": "single_select_card",
                    "question": "How does your skin react to sun?",
                    "subtitle": "This is the Fitzpatrick scale — it helps JAY recommend the right SPF and brightening products",
                    "options": [
                        {
                            "value": 1,
                            "label": "Type I",
                            "description": "Always burns, never tans. Very fair skin.",
                        },
                        {
                            "value": 2,
                            "label": "Type II",
                            "description": "Burns easily, tans minimally. Fair skin.",
                        },
                        {
                            "value": 3,
                            "label": "Type III",
                            "description": "Sometimes burns, tans gradually. Medium skin.",
                        },
                        {
                            "value": 4,
                            "label": "Type IV",
                            "description": "Rarely burns, tans easily. Olive/medium-brown skin.",
                        },
                        {
                            "value": 5,
                            "label": "Type V",
                            "description": "Very rarely burns, tans darkly. Brown skin.",
                        },
                        {
                            "value": 6,
                            "label": "Type VI",
                            "description": "Never burns, deeply pigmented. Dark brown/black skin.",
                        },
                    ],
                    "required": False,
                },
                {
                    "id": "primary_concerns",
                    "type": "multi_select_chip",
                    "question": "What are your top skin concerns?",
                    "subtitle": "Pick up to 3 — we know there are more, but let's focus",
                    "validation": {"max_select": 3},
                    "options": [
                        {"value": "acne", "label": "Acne & breakouts", "emoji": "😤"},
                        {"value": "dark_spots", "label": "Dark spots & pigmentation", "emoji": "🔵"},
                        {"value": "wrinkles", "label": "Fine lines & wrinkles", "emoji": "〰️"},
                        {"value": "pores", "label": "Large pores", "emoji": "🔍"},
                        {"value": "texture", "label": "Uneven texture", "emoji": "🪨"},
                        {"value": "dullness", "label": "Dullness", "emoji": "😶"},
                        {"value": "dark_circles", "label": "Dark circles", "emoji": "🐼"},
                        {"value": "tan", "label": "Tan & sun damage", "emoji": "☀️"},
                        {"value": "oiliness", "label": "Excess oil", "emoji": "💦"},
                        {"value": "dryness", "label": "Dryness & flaking", "emoji": "🏜️"},
                        {"value": "sensitivity", "label": "Sensitivity & redness", "emoji": "🌡️"},
                        {"value": "aging", "label": "Signs of aging", "emoji": "⏳"},
                    ],
                    "required": True,
                },
                {
                    "id": "skin_feel_midday",
                    "type": "single_select",
                    "question": "How does your skin feel by midday?",
                    "subtitle": "Be honest — no one's judging your T-zone",
                    "options": [
                        {"value": "oily_all_over", "label": "Oily all over — I could fry an egg"},
                        {"value": "oily_t_zone", "label": "Oily T-zone, rest is fine"},
                        {"value": "comfortable", "label": "Comfortable — no complaints"},
                        {"value": "tight_dry", "label": "Tight and dry — need moisture ASAP"},
                        {"value": "varies", "label": "Depends on the day honestly"},
                    ],
                    "required": False,
                },
                {
                    "id": "skin_history",
                    "type": "multi_select_chip",
                    "question": "Any skin conditions, past or present?",
                    "subtitle": "No shame — these are more common than you think",
                    "options": [
                        {"value": "eczema", "label": "Eczema"},
                        {"value": "psoriasis", "label": "Psoriasis"},
                        {"value": "rosacea", "label": "Rosacea"},
                        {"value": "dermatitis", "label": "Dermatitis"},
                        {"value": "fungal_acne", "label": "Fungal acne"},
                        {"value": "melasma", "label": "Melasma"},
                        {"value": "vitiligo", "label": "Vitiligo"},
                        {"value": "cystic_acne", "label": "Cystic acne"},
                        {"value": "hormonal_acne", "label": "Hormonal acne"},
                        {"value": "none", "label": "None of these"},
                    ],
                    "required": False,
                },
                {
                    "id": "allergies",
                    "type": "tag_input",
                    "question": "Any known allergies?",
                    "subtitle": "Ingredients, fragrances, preservatives — anything your skin hates",
                    "placeholder": "Type and press enter (e.g. fragrance, parabens, nickel)",
                    "suggestions": [
                        "fragrance",
                        "parabens",
                        "sulfates",
                        "nickel",
                        "lanolin",
                        "formaldehyde",
                        "latex",
                        "coconut oil",
                        "essential oils",
                    ],
                    "required": False,
                },
                {
                    "id": "sensitivities",
                    "type": "multi_select_chip",
                    "question": "What irritates your skin?",
                    "subtitle": "Products that make your skin throw a tantrum",
                    "options": [
                        {"value": "fragrance", "label": "Fragrance"},
                        {"value": "alcohol", "label": "Alcohol (denat.)"},
                        {"value": "retinol", "label": "Retinol"},
                        {"value": "aha_bha", "label": "AHA/BHA acids"},
                        {"value": "vitamin_c", "label": "Vitamin C (L-ascorbic)"},
                        {"value": "essential_oils", "label": "Essential oils"},
                        {"value": "niacinamide", "label": "Niacinamide"},
                        {"value": "sulfates", "label": "Sulfates"},
                        {"value": "silicones", "label": "Silicones"},
                        {"value": "not_sure", "label": "Not sure yet"},
                    ],
                    "required": False,
                },
            ],
        },
        {
            "id": "skin_state",
            "title": "Skin check-in",
            "subtitle": "How's your skin doing RIGHT NOW? Be brutally honest.",
            "icon": "scan",
            "questions": [
                {
                    "id": "acne_level",
                    "type": "slider",
                    "question": "Acne level right now",
                    "min": 0,
                    "max": 5,
                    "step": 1,
                    "labels": {
                        "0": "Clear skies",
                        "1": "A spot or two",
                        "2": "A few unwanted guests",
                        "3": "Party on my face",
                        "4": "Breakout city",
                        "5": "Code red",
                    },
                    "required": True,
                },
                {
                    "id": "oiliness_level",
                    "type": "slider",
                    "question": "Oiliness level",
                    "min": 0,
                    "max": 5,
                    "step": 1,
                    "labels": {
                        "0": "Sahara desert",
                        "1": "Matte and happy",
                        "2": "Slight shine",
                        "3": "Noticeable",
                        "4": "Oil slick",
                        "5": "BP called, they want their oil back",
                    },
                    "required": True,
                },
                {
                    "id": "dryness_level",
                    "type": "slider",
                    "question": "Dryness level",
                    "min": 0,
                    "max": 5,
                    "step": 1,
                    "labels": {
                        "0": "Nope, hydrated",
                        "1": "Slightly tight",
                        "2": "Needs moisture",
                        "3": "Flaking in spots",
                        "4": "Peeling",
                        "5": "Crocodile mode",
                    },
                    "required": True,
                },
                {
                    "id": "irritation_level",
                    "type": "slider",
                    "question": "Irritation / redness",
                    "min": 0,
                    "max": 5,
                    "step": 1,
                    "labels": {
                        "0": "Calm and collected",
                        "1": "Tiny bit pink",
                        "2": "Mildly irritated",
                        "3": "Red patches",
                        "4": "Angry skin",
                        "5": "Full tomato",
                    },
                    "required": True,
                },
                {
                    "id": "new_breakouts",
                    "type": "yes_no",
                    "question": "Any new breakouts in the last week?",
                    "subtitle": "Fresh uninvited guests, not the ones that have been camping on your face",
                    "required": True,
                },
                {
                    "id": "overall_feeling",
                    "type": "emoji_select",
                    "question": "Overall, how does your skin feel today?",
                    "options": [
                        {"value": "great", "label": "Glowing", "emoji": "✨"},
                        {"value": "good", "label": "Good", "emoji": "😊"},
                        {"value": "okay", "label": "Okay", "emoji": "😐"},
                        {"value": "bad", "label": "Not great", "emoji": "😞"},
                        {"value": "terrible", "label": "Terrible", "emoji": "😫"},
                    ],
                    "required": True,
                },
            ],
        },
        {
            "id": "routine",
            "title": "Your current game plan",
            "subtitle": "What are you already doing? No wrong answers — even 'nothing' counts.",
            "icon": "clock",
            "questions": [
                {
                    "id": "am_steps",
                    "type": "multi_select_ordered",
                    "question": "What's your morning routine?",
                    "subtitle": "Select in order — drag to rearrange",
                    "options": [
                        {"value": "cleanser", "label": "Cleanser / Face wash"},
                        {"value": "toner", "label": "Toner"},
                        {"value": "serum", "label": "Serum"},
                        {"value": "moisturizer", "label": "Moisturizer"},
                        {"value": "sunscreen", "label": "Sunscreen"},
                        {"value": "eye_cream", "label": "Eye cream"},
                        {"value": "face_oil", "label": "Face oil"},
                        {"value": "mist", "label": "Face mist / Setting spray"},
                        {"value": "lip_balm", "label": "Lip balm"},
                        {"value": "nothing", "label": "Nothing — I just exist"},
                    ],
                    "required": False,
                },
                {
                    "id": "pm_steps",
                    "type": "multi_select_ordered",
                    "question": "What's your night routine?",
                    "subtitle": "The PM routine is where the magic happens",
                    "options": [
                        {"value": "oil_cleanser", "label": "Oil cleanser / Makeup remover"},
                        {"value": "cleanser", "label": "Cleanser / Face wash"},
                        {"value": "exfoliant", "label": "Exfoliant (AHA/BHA)"},
                        {"value": "toner", "label": "Toner"},
                        {"value": "serum", "label": "Serum / Treatment"},
                        {"value": "retinol", "label": "Retinol / Retinoid"},
                        {"value": "eye_cream", "label": "Eye cream"},
                        {"value": "moisturizer", "label": "Moisturizer / Night cream"},
                        {"value": "face_oil", "label": "Face oil"},
                        {"value": "spot_treatment", "label": "Spot treatment"},
                        {"value": "sleeping_mask", "label": "Sleeping mask"},
                        {"value": "nothing", "label": "Pillow is my skincare"},
                    ],
                    "required": False,
                },
                {
                    "id": "routine_consistency",
                    "type": "single_select",
                    "question": "How consistent are you?",
                    "subtitle": "Consistency beats a 12-step routine you do once a month. Every. Single. Time.",
                    "options": [
                        {"value": "daily", "label": "Every single day — rain or shine"},
                        {"value": "most_days", "label": "Most days — I try"},
                        {"value": "sometimes", "label": "When I remember"},
                        {"value": "rarely", "label": "What routine?"},
                    ],
                    "required": False,
                },
                {
                    "id": "products_currently_using",
                    "type": "tag_input",
                    "question": "What products are you currently using?",
                    "subtitle": "Brand names, product names — whatever you remember. No judgment on the expired sunscreen.",
                    "placeholder": "e.g. Cetaphil Gentle Cleanser",
                    "suggestions": [
                        "Cetaphil Gentle Cleanser",
                        "Minimalist SPF 50",
                        "Simple Face Wash",
                        "Neutrogena Sunscreen",
                        "Nivea Moisturizer",
                        "The Ordinary Niacinamide",
                        "Dot & Key Moisturizer",
                        "Plum Green Tea Toner",
                        "Himalaya Neem Face Wash",
                        "Lakme Sun Expert",
                        "Re'equil Sunscreen",
                        "Biotique Aloe Vera Gel",
                    ],
                    "required": False,
                },
                {
                    "id": "how_long_current_routine",
                    "type": "single_select",
                    "question": "How long have you been on this routine?",
                    "subtitle": "Skin needs 4-6 weeks to show results from a new routine",
                    "options": [
                        {"value": "less_than_month", "label": "Less than a month"},
                        {"value": "1_3_months", "label": "1-3 months"},
                        {"value": "3_6_months", "label": "3-6 months"},
                        {"value": "6_plus_months", "label": "6+ months"},
                        {"value": "over_a_year", "label": "Over a year"},
                        {"value": "no_routine", "label": "I don't have a routine"},
                    ],
                    "required": False,
                },
            ],
        },
        {
            "id": "lifestyle",
            "title": "Life outside skincare",
            "subtitle": "Your skin is a mirror of your lifestyle — let's connect the dots",
            "icon": "heart",
            "questions": [
                {
                    "id": "physical_activity",
                    "type": "single_select",
                    "question": "How active are you?",
                    "subtitle": "Exercise increases blood flow and helps your skin glow",
                    "options": [
                        {"value": "sedentary", "label": "Sedentary — desk life"},
                        {"value": "light", "label": "Light — walks and stretching"},
                        {"value": "moderate", "label": "Moderate — 3-4x/week workouts"},
                        {"value": "active", "label": "Active — daily exercise"},
                        {"value": "very_active", "label": "Very active — athlete level"},
                    ],
                    "required": False,
                },
                {
                    "id": "water_intake_glasses",
                    "type": "slider",
                    "question": "How many glasses of water do you drink daily?",
                    "subtitle": "Hydration from the inside matters more than any moisturizer",
                    "min": 0,
                    "max": 15,
                    "step": 1,
                    "labels": {
                        "0": "Does coffee count?",
                        "4": "Getting there",
                        "8": "Solid",
                        "12": "Hydration hero",
                        "15": "Aquaman",
                    },
                    "required": False,
                },
                {
                    "id": "sleep_hours",
                    "type": "slider",
                    "question": "How many hours of sleep do you get?",
                    "subtitle": "They don't call it beauty sleep for nothing",
                    "min": 0,
                    "max": 12,
                    "step": 0.5,
                    "labels": {
                        "0": "Barely",
                        "4": "Surviving",
                        "6": "Could be better",
                        "8": "Ideal",
                        "10": "Blessed",
                        "12": "Hibernating",
                    },
                    "required": False,
                },
                {
                    "id": "sleep_quality",
                    "type": "single_select",
                    "question": "How's the quality of your sleep?",
                    "subtitle": "8 hours of tossing and turning doesn't count",
                    "options": [
                        {"value": "great", "label": "Great — out like a light"},
                        {"value": "good", "label": "Good — mostly restful"},
                        {"value": "okay", "label": "Okay — could be better"},
                        {"value": "poor", "label": "Poor — wake up tired"},
                        {"value": "terrible", "label": "Terrible — what is sleep?"},
                    ],
                    "required": False,
                },
                {
                    "id": "sun_exposure",
                    "type": "single_select",
                    "question": "How much sun do you get daily?",
                    "subtitle": "UV is the #1 cause of premature aging. Yes, even through windows.",
                    "options": [
                        {"value": "minimal", "label": "Minimal — mostly indoors"},
                        {"value": "moderate", "label": "Moderate — commute + some outdoor time"},
                        {"value": "high", "label": "High — outdoors a lot"},
                        {"value": "very_high", "label": "Very high — outdoor job or lifestyle"},
                    ],
                    "required": False,
                },
                {
                    "id": "sun_protection_habit",
                    "type": "single_select",
                    "question": "Do you wear sunscreen?",
                    "subtitle": "If you skip this one, everything else is just expensive moisturizing",
                    "options": [
                        {"value": "always", "label": "Always — even indoors"},
                        {"value": "mostly", "label": "Mostly — when I remember"},
                        {"value": "sometimes", "label": "Sometimes — only outdoors"},
                        {"value": "rarely", "label": "Rarely"},
                        {"value": "never", "label": "Never — judge me"},
                    ],
                    "required": False,
                },
                {
                    "id": "diet_type",
                    "type": "single_select",
                    "question": "What's your diet like?",
                    "subtitle": "Your gut and your skin are best friends — or worst enemies",
                    "options": [
                        {"value": "vegetarian", "label": "Vegetarian"},
                        {"value": "non_vegetarian", "label": "Non-vegetarian"},
                        {"value": "vegan", "label": "Vegan"},
                        {"value": "eggetarian", "label": "Eggetarian"},
                        {"value": "pescatarian", "label": "Pescatarian"},
                        {"value": "flexitarian", "label": "Flexitarian"},
                    ],
                    "required": False,
                },
                {
                    "id": "dairy_consumption",
                    "type": "single_select",
                    "question": "How often do you consume dairy?",
                    "subtitle": "Dairy and acne have a complicated relationship",
                    "options": [
                        {"value": "daily", "label": "Daily"},
                        {"value": "often", "label": "Often (4-5x/week)"},
                        {"value": "sometimes", "label": "Sometimes (2-3x/week)"},
                        {"value": "rarely", "label": "Rarely"},
                        {"value": "never", "label": "Never"},
                    ],
                    "required": False,
                },
                {
                    "id": "sugar_consumption",
                    "type": "single_select",
                    "question": "How's your sugar intake?",
                    "subtitle": "Sugar → insulin spike → inflammation → breakouts. Your Bournville habit has consequences.",
                    "options": [
                        {"value": "daily", "label": "Daily — sweet tooth for life"},
                        {"value": "often", "label": "Often"},
                        {"value": "sometimes", "label": "Sometimes — I try to limit"},
                        {"value": "rarely", "label": "Rarely"},
                        {"value": "never", "label": "Never"},
                    ],
                    "required": False,
                },
                {
                    "id": "spicy_food",
                    "type": "single_select",
                    "question": "Spicy food tolerance?",
                    "subtitle": "Spicy food can trigger rosacea and flushing in some people",
                    "options": [
                        {"value": "love_it", "label": "Love it — bring the heat"},
                        {"value": "moderate", "label": "Moderate — some spice is nice"},
                        {"value": "mild", "label": "Mild — I'm delicate"},
                        {"value": "avoid", "label": "Avoid — my stomach says no"},
                    ],
                    "required": False,
                },
                {
                    "id": "smoking",
                    "type": "single_select",
                    "question": "Do you smoke?",
                    "subtitle": "Smoking ages skin 2x faster — not a lecture, just data",
                    "options": [
                        {"value": "never", "label": "Never"},
                        {"value": "occasionally", "label": "Occasionally / socially"},
                        {"value": "regularly", "label": "Regularly"},
                        {"value": "quit", "label": "Quit — proud of it"},
                    ],
                    "required": False,
                },
                {
                    "id": "alcohol",
                    "type": "single_select",
                    "question": "Alcohol consumption?",
                    "subtitle": "Alcohol dehydrates your skin from the inside out",
                    "options": [
                        {"value": "never", "label": "Never"},
                        {"value": "occasionally", "label": "Occasionally"},
                        {"value": "socially", "label": "Socially (weekends)"},
                        {"value": "regularly", "label": "Regularly"},
                    ],
                    "required": False,
                },
                {
                    "id": "stress_level",
                    "type": "single_select",
                    "question": "Current stress level?",
                    "subtitle": "Cortisol (stress hormone) triggers oil production and breakouts",
                    "options": [
                        {"value": "low", "label": "Low — life is good"},
                        {"value": "moderate", "label": "Moderate — manageable"},
                        {"value": "high", "label": "High — it's a lot right now"},
                        {"value": "very_high", "label": "Very high — need a vacation"},
                    ],
                    "required": False,
                },
                {
                    "id": "screen_time_hours",
                    "type": "slider",
                    "question": "Daily screen time?",
                    "subtitle": "Blue light from screens can cause pigmentation — yes, really",
                    "min": 0,
                    "max": 16,
                    "step": 0.5,
                    "labels": {
                        "0": "Touching grass",
                        "4": "Normal",
                        "8": "Heavy user",
                        "12": "Digital native",
                        "16": "Screen is life",
                    },
                    "required": False,
                },
                {
                    "id": "travel_frequency",
                    "type": "single_select",
                    "question": "How often do you travel?",
                    "subtitle": "Changing climates and water sources can wreck your skin",
                    "options": [
                        {"value": "rarely", "label": "Rarely — homebody"},
                        {"value": "monthly", "label": "Monthly"},
                        {"value": "weekly", "label": "Weekly"},
                        {"value": "constantly", "label": "Constantly — nomad life"},
                    ],
                    "required": False,
                },
            ],
        },
        {
            "id": "preferences",
            "title": "Your preferences",
            "subtitle": "What does your ideal skincare world look like?",
            "icon": "sliders",
            "questions": [
                {
                    "id": "budget_range",
                    "type": "single_select_card",
                    "question": "Monthly skincare budget?",
                    "subtitle": "Good skincare exists at every price point — JAY will work with yours",
                    "options": [
                        {"value": "under_500", "label": "Under ₹500", "description": "Budget-friendly finds"},
                        {"value": "500_1000", "label": "₹500 – ₹1,000", "description": "Smart mid-range"},
                        {"value": "1000_2000", "label": "₹1,000 – ₹2,000", "description": "Investing in skin"},
                        {"value": "2000_plus", "label": "₹2,000+", "description": "Premium picks"},
                        {"value": "no_limit", "label": "No limit", "description": "Whatever works, works"},
                    ],
                    "required": False,
                },
                {
                    "id": "product_preference",
                    "type": "single_select_card",
                    "question": "What kind of products do you prefer?",
                    "subtitle": "This helps JAY recommend brands you'll actually like",
                    "options": [
                        {"value": "pharmacy", "label": "Pharmacy / Dermat", "description": "CeraVe, Cetaphil, La Roche-Posay — science-first"},
                        {"value": "luxury", "label": "Luxury", "description": "Clinique, Estée Lauder, SK-II — the fancy shelf"},
                        {"value": "natural", "label": "Natural / Clean", "description": "Plum, Juicy Chemistry — ingredient-conscious"},
                        {"value": "korean", "label": "K-Beauty", "description": "COSRX, Innisfree, Laneige — glass skin goals"},
                        {"value": "ayurvedic", "label": "Ayurvedic", "description": "Forest Essentials, Kama Ayurveda — traditional wisdom"},
                        {"value": "no_preference", "label": "No preference", "description": "If it works, it works"},
                    ],
                    "required": False,
                },
                {
                    "id": "ingredient_preference",
                    "type": "single_select",
                    "question": "Ingredient philosophy?",
                    "subtitle": "There's no wrong answer — just your comfort zone",
                    "options": [
                        {"value": "clean_only", "label": "Clean beauty only — minimal ingredients"},
                        {"value": "science_backed", "label": "Science-backed — give me the actives"},
                        {"value": "natural_only", "label": "Natural only — no chemicals"},
                        {"value": "no_preference", "label": "No preference — whatever works"},
                    ],
                    "required": False,
                },
                {
                    "id": "fragrance_preference",
                    "type": "single_select",
                    "question": "How do you feel about fragrance in products?",
                    "subtitle": "Fragrance is the #1 cause of contact dermatitis in skincare",
                    "options": [
                        {"value": "love", "label": "Love it — part of the experience"},
                        {"value": "neutral", "label": "Neutral — don't care either way"},
                        {"value": "prefer_unscented", "label": "Prefer unscented"},
                        {"value": "strictly_unscented", "label": "Strictly unscented — sensitive skin"},
                    ],
                    "required": False,
                },
                {
                    "id": "remedy_openness",
                    "type": "single_select",
                    "question": "Open to home remedies?",
                    "subtitle": "Turmeric, honey, aloe vera... grandma's arsenal",
                    "options": [
                        {"value": "love_home_remedies", "label": "Love them — grandma knows best"},
                        {"value": "open_to_trying", "label": "Open to trying — if there's science behind it"},
                        {"value": "prefer_products", "label": "Prefer products — but occasional DIY is fine"},
                        {"value": "products_only", "label": "Products only — keep the kitchen in the kitchen"},
                    ],
                    "required": False,
                },
                {
                    "id": "routine_complexity",
                    "type": "single_select_card",
                    "question": "How complex do you want your routine?",
                    "subtitle": "Remember: consistency > complexity",
                    "options": [
                        {"value": "minimal_1_3", "label": "Minimal (1-3 steps)", "description": "Cleanser, moisturizer, sunscreen — done"},
                        {"value": "moderate_4_5", "label": "Moderate (4-5 steps)", "description": "The sweet spot for most people"},
                        {"value": "elaborate_6_plus", "label": "Elaborate (6+ steps)", "description": "Full K-beauty, layering, the works"},
                        {"value": "whatever_works", "label": "Whatever works", "description": "JAY, you decide"},
                    ],
                    "required": False,
                },
                {
                    "id": "top_goal",
                    "type": "single_select_card",
                    "question": "If you could fix ONE thing, what would it be?",
                    "subtitle": "Pick your final boss. JAY will build your entire strategy around defeating it.",
                    "options": [
                        {"value": "clear_skin", "label": "Clear skin", "description": "No more breakouts", "emoji": "✨"},
                        {"value": "anti_aging", "label": "Anti-aging", "description": "Prevent and reverse", "emoji": "⏳"},
                        {"value": "glow", "label": "Glow", "description": "That lit-from-within look", "emoji": "🌟"},
                        {"value": "even_tone", "label": "Even skin tone", "description": "Bye dark spots and pigmentation", "emoji": "🎨"},
                        {"value": "hydration", "label": "Hydration", "description": "Plump, dewy, moisturized", "emoji": "💧"},
                        {"value": "oil_control", "label": "Oil control", "description": "Matte and fresh all day", "emoji": "🧴"},
                    ],
                    "required": True,
                },
                {
                    "id": "willing_to_try_prescription",
                    "type": "yes_no",
                    "question": "Open to prescription products?",
                    "subtitle": "The big guns — tretinoin, adapalene, and the stuff that needs a doctor's signature",
                    "required": False,
                },
                {
                    "id": "preferred_texture",
                    "type": "multi_select_chip",
                    "question": "What textures do you prefer?",
                    "subtitle": "Texture matters — if you hate how it feels, you won't use it",
                    "options": [
                        {"value": "gel", "label": "Gel — lightweight"},
                        {"value": "cream", "label": "Cream — rich"},
                        {"value": "lotion", "label": "Lotion — in between"},
                        {"value": "serum", "label": "Serum — watery"},
                        {"value": "oil", "label": "Oil — dewy"},
                        {"value": "balm", "label": "Balm — thick"},
                        {"value": "foam", "label": "Foam — airy"},
                        {"value": "no_preference", "label": "No preference"},
                    ],
                    "required": False,
                },
                {
                    "id": "shopping_preference",
                    "type": "single_select",
                    "question": "Where do you prefer to buy skincare?",
                    "subtitle": "So JAY can recommend where to find products",
                    "options": [
                        {"value": "online", "label": "Online — Nykaa, Amazon, brand websites"},
                        {"value": "offline", "label": "Offline — stores, pharmacies"},
                        {"value": "both", "label": "Both — wherever the deal is better"},
                    ],
                    "required": False,
                },
            ],
        },
    ],
    "completion_rewards": {
        "basics": {"points": 5, "message": "JAY now knows your name!"},
        "skin": {"points": 10, "message": "Your skin identity is mapped"},
        "skin_state": {"points": 5, "message": "Current state logged"},
        "routine": {"points": 5, "message": "JAY knows your shelf now"},
        "lifestyle": {"points": 10, "message": "The full picture is forming"},
        "preferences": {"points": 5, "message": "Personalization complete!"},
    },
    "total_bonus_points": 20,
}
